title: Anna Matvieieva
logo: img/round-head-screenschot.png
description: Aspiring Data Analyst & Future Data Wizard.\nTurning raw data into meaningful insights one query at a time.
schow_downloads: true
remote_theme: remote_theme: pages-themes/minimal@v0.2.0
