title: Anna Matvieieva
logo: img/round-head-screenschot.png
description: Motivierte Betriebswirtin mit soliden Kenntnissen in Python,
SQL und Datenvisualisierung (Excel, Tableau).
Ich bringe starke analytische Fähigkeiten, eine strukturierte
Arbeitsweise und hohe Lernbereitschaft mit. Mein Ziel ist es,
datenbasierte Entscheidungsprozesse zu unterstützen und
mich in einem dynamischen Umfeld weiterzuentwickeln.
schow_downloads: true
remote_theme: pages-themes/cayman

